<?php
// $Id$

/**
 * @file
 * Checks to see if your installed modules are available for the next major
 * release of Drupal.
 */

/**
 * Implementation of hook_help().
 */
function upgrade_status_help($path, $arg) {
  switch ($path) {
    case 'admin/help#module':
      $file = drupal_get_path('module', 'upgrade_status') .'/README.txt';
      if (file_exists($file)) {
        return _filter_autop(file_get_contents($file));
      }
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function upgrade_status_menu() {
  $items['admin/reports/updates/upgrade'] = array(
    'title' => 'Upgrade status',
    'page callback' => 'upgrade_status_status',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'upgrade_status.admin.inc'
  );
  $items['admin/reports/updates/upgrade/check'] = array(
    'page callback' => 'upgrade_status_manual_status',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'upgrade_status.admin.inc'
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function upgrade_status_theme() {
  return array(
    'upgrade_status_report' => array(
      'arguments' => array('data' => NULL),
      'file' => 'upgrade_status.admin.inc',
    ),
    'upgrade_status_version' => array(
      'arguments' => array('version' => NULL, 'tag' => NULL, 'class' => NULL),
      'file' => 'upgrade_status.admin.inc',
    ),
  );
}

