<?php
// $Id$

/**
 * @file
 * Checks to see if your installed modules are available for the next major
 * release of Drupal.
 */

/**
 * Implementation of hook_help().
 */
function upgrade_status_help($section) {
  switch ($section) {
    case 'admin/help#module':
      $file = drupal_get_path('module', 'upgrade_status') .'/README.txt';
      if (file_exists($file)) {
        return _filter_autop(file_get_contents($file));
      }
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function upgrade_status_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $admin_access = user_access('administer site configuration');
    $items[] = array(
      'path' => 'admin/logs/updates/upgrade',
      'title' => t('Upgrade status'),
      'callback' => 'upgrade_status_status',
      'access' => $admin_access,
      'type' => MENU_LOCAL_TASK,
      'weight' => 10,
    );
    $items[] = array(
      'path' => 'admin/logs/updates/upgrade/check',
      'callback' => 'upgrade_status_manual_status',
      'access' => $admin_access,
      'type' => MENU_CALLBACK,
    );
  }
  return $items;
}

/**
 * Menu callback. Generate a page about the upgrade status of projects.
 *
 * Stub function for Drupal 5.x.
 */
function upgrade_status_status() {
  require_once drupal_get_path('module', 'upgrade_status') .'/upgrade_status.admin.inc';
  return _upgrade_status_status();
}

/**
 * Menu callback to manually check the upgrade status.
 *
 * Stub function for Drupal 5.x.
 */
function upgrade_status_manual_status() {
  require_once drupal_get_path('module', 'upgrade_status') .'/upgrade_status.admin.inc';
  return _upgrade_status_manual_status();
}

